### ISSUE TITLE
federation control plane panic

### ISSUE THREAD

**Issue by qinpingli** [kubernetes-sigs/federation-v2#491]
Logs:
Federation v2 controller-manager version: version.Info{Version:"v0.0.3-126-g7906b8cd", GitCommit:"7906b8cdb73334930ea9dd7e2871a4bbbe5af176", GitTreeState:"clean", BuildDate:"2018-12-06T02:42:38Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
I1206 06:52:48.991785       1 controller-manager.go:100] Federation will target all namespaces
I1206 06:52:48.992888       1 controller.go:84] Starting cluster controller
I1206 06:52:48.993635       1 controller.go:65] Starting scheduler controller
I1206 06:52:49.285852       1 controller.go:116] Running reconcile FederatedTypeConfig for "federation-system/deployments.apps"
I1206 06:52:49.286277       1 controller.go:91] Starting ServiceDNS controller
I1206 06:52:49.287261       1 controller.go:82] Starting IngressDNS controller
I1206 06:52:49.287581       1 controller.go:76] Starting FederatedTypeConfig controller
I1206 06:52:49.287760       1 controller.go:83] Starting replicaschedulingpreferences controller
I1206 06:52:49.287810       1 controller.go:168] Start plugin with kind FederatedDeployment for scheduling type ReplicaSchedulingPreference
E1206 06:52:49.288679       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:63
/usr/local/go/src/runtime/signal_unix.go:388
/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/util/resourceclient.go:37
/go/src/github.com/kubernetes-sigs/federation-v2/pkg/schedulingtypes/plugin.go:100
/go/src/github.com/kubernetes-sigs/federation-v2/pkg/schedulingtypes/replicascheduler.go:99
/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/schedulingmanager/controller.go:169
/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/schedulingmanager/controller.go:78
/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/util/worker.go:156
/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/util/worker.go:119
/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x10339fc]

goroutine 55 [running]:
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x11f6b00, 0x1d12780)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/kubernetes-sigs/federation-v2/pkg/controller/util.NewResourceClient(0x14a9460, 0xc420721100, 0x0, 0x0, 0xc42029c1c0, 0x14c94e0, 0xc420617f60)
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/util/resourceclient.go:37 +0x4c
github.com/kubernetes-sigs/federation-v2/pkg/schedulingtypes.NewPlugin(0xc4200b46e0, 0xc42029c1c0, 0xc4205d7180, 0xc4205d7190, 0x14c9ea0, 0xc420707b00, 0xc420714500, 0x1c, 0xc4201eb9f8)
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/schedulingtypes/plugin.go:100 +0x70d
github.com/kubernetes-sigs/federation-v2/pkg/schedulingtypes.(*ReplicaScheduler).StartPlugin(0xc420656f00, 0x14c9ea0, 0xc420707b00, 0xc4200a2420, 0x2, 0x14c8b80)
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/schedulingtypes/replicascheduler.go:99 +0xd5
github.com/kubernetes-sigs/federation-v2/pkg/controller/schedulingmanager.(*SchedulerController).reconcile(0xc420264960, 0xc420714460, 0x11, 0xc4201eb8e0, 0x10, 0xc420633080)
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/schedulingmanager/controller.go:169 +0x6e7
github.com/kubernetes-sigs/federation-v2/pkg/controller/schedulingmanager.(*SchedulerController).(github.com/kubernetes-sigs/federation-v2/pkg/controller/schedulingmanager.reconcile)-fm(0xc420714460, 0x11, 0xc4201eb8e0, 0x10, 0xc42011d520)
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/schedulingmanager/controller.go:78 +0x52
github.com/kubernetes-sigs/federation-v2/pkg/controller/util.(*asyncWorker).worker(0xc420264a00)
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/util/worker.go:156 +0xb0
github.com/kubernetes-sigs/federation-v2/pkg/controller/util.(*asyncWorker).(github.com/kubernetes-sigs/federation-v2/pkg/controller/util.worker)-fm()
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/util/worker.go:119 +0x2a
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc4204d8010)
	/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc4204d8010, 0x3b9aca00, 0x0, 0xc42011bf01, 0xc4200a2420)
	/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc4204d8010, 0x3b9aca00, 0xc4200a2420)
	/go/src/github.com/kubernetes-sigs/federation-v2/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/kubernetes-sigs/federation-v2/pkg/controller/util.(*asyncWorker).Run
	/go/src/github.com/kubernetes-sigs/federation-v2/pkg/controller/util/worker.go:119 +0xef

**Comment by marun** [comment]
It would be helpful to know the version of the control plane, the arguments used to start it, and what federated type configs are present (if any).    Given that the control plane is constantly being run in CI, I suspect a problem with the environment (i.e. maybe the controller has a dependency on a certain system state that is guaranteed in CI but not true of your environment).

**Comment by qinpingli** [comment]
image tag is: canary,  image tag=latest no this issue.

No federatedtypeconfig was created.

Deployed federation control plane on openshift v3.11
Deploy steps:
1) create namespace `federation-system`, `kube-multicluster-public` on hostcluster
2) oc create clusterrolebinding federation-admin --clusterrole=cluster-admin --serviceaccount="federation-system:default"
3) oc apply --validate=false -f https://raw.githubusercontent.com/kubernetes-sigs/federation-v2/master/vendor/k8s.io/cluster-registry/cluster-registry-crd.yaml
4) oc -n federation-system apply --validate=false -f ./install-latest.yaml #here use the image with tag canary
5) ./kubefed2 join "cluster1" --host-cluster-context "cluster1" --add-to-registry --v=2 --federation-namespace=federation-system
6) ./kubefed2 join "cluster2" --host-cluster-context "cluster1" --add-to-registry --v=2 --federation-namespace=federation-system

**Comment by qinpingli** [comment]
Reproduced the issue, changed image tag from `latest` to `canary`.
Run the command:
./kubefed2 federate enable Namespace -f ./federatedirectives/namespaces.yaml --host-cluster-context=cluster1
./kubefed2.latest federate enable Deployment --override-paths=spec.replicas -f ./federatedirectives/deployments.apps.yaml --host-cluster-context=cluster1

**Comment by gyliu513** [comment]
@qinpingli Your second command failed in my cluster as follows, am I missing anything?

```
root@gyliu-dev1:~/go/src/github.com/kubernetes-sigs/federation-v2# ./bin/kubefed2 federate enable federate enable Deployment --override-paths=spec.replicas -f  ./config/federatedirectives/deployments.apps.yaml --host-cluster-context=cluster1 --dry-run -oyaml
Error: unknown flag: --override-paths
Usage:
  kubefed2 federate enable NAME [flags]

Examples:

		# Enable federation of Services with service type overrideable
		kubefed2 federate enable Service --override-paths=spec.type --host-cluster-context=cluster1

Flags:
      --comparison-field string       The field in the target type to compare for equality. Valid values are "ResourceVersion" (default) and "Generation". (default "ResourceVersion")
      --dry-run                       Run the command in dry-run mode, without making any server requests.
      --federation-namespace string   Namespace in the host cluster where the federation system components are installed.  This namespace will also be the target of propagation if the controller manager is configured with --limited-scope and clusters are joined with --limited-scope. (default "federation-system")
  -f, --filename string               If provided, the command will be configured from the provided yaml file.  Only --output wll be accepted from the command line
  -h, --help                          help for enable
      --host-cluster-context string   Host cluster context
      --kubeconfig string             Path to the kubeconfig file to use for CLI requests.
  -o, --output string                 If provided, the resources that will be created in the API will be output to stdout in the provided format.  Valid values are ['yaml'].
      --primitive-group string        The name of the API group to use for generated federation primitives. (default "primitives.federation.k8s.io")
      --primitive-version string      The API version to use for generated federation primitives. (default "v1alpha1")
      --registry-namespace string     Namespace in the host cluster where clusters are registered (default "kube-multicluster-public")
      --version string                Optional, the API version of the target type.

Global Flags:
      --alsologtostderr                  log to standard error as well as files
      --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log-dir string                   If non-empty, write log files in this directory
      --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
      --logtostderr                      log to standard error instead of files (default true)
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

unknown flag: --override-paths
```

**Comment by gyliu513** [comment]
Another question is install federation via `install-latest.yaml` and then update image from `latest` to `canary` may also have some issues, as `install-latest.yaml` may lack some CRD resources compared with the install file generated by `canary` image.

If you want to test via the `canary` image, then I suggest you install federation via helm chart or you may want to re-generate a `install.yaml` via command like this https://github.com/kubernetes-sigs/federation-v2/blob/master/scripts/generate-install-yaml.sh#L25-L26 with `canary` image.

Why not install the federation with following command:

```
scripts/deploy-federation.sh quay.io/kubernetes-multicluster/federation-v2:canary cluster2
```

The above command can enable you test with `canary` image.

**Comment by qinpingli** [comment]
> @qinpingli Your second command failed in my cluster as follows, am I missing anything?
> 
> ```
> root@gyliu-dev1:~/go/src/github.com/kubernetes-sigs/federation-v2# ./bin/kubefed2 federate enable federate enable Deployment --override-paths=spec.replicas -f  ./config/federatedirectives/deployments.apps.yaml --host-cluster-context=cluster1 --dry-run -oyaml
> Error: unknown flag: --override-paths
> Usage:
>   kubefed2 federate enable NAME [flags]
> 
> Examples:
> 
> 		# Enable federation of Services with service type overrideable
> 		kubefed2 federate enable Service --override-paths=spec.type --host-cluster-context=cluster1
> 
> Flags:
>       --comparison-field string       The field in the target type to compare for equality. Valid values are "ResourceVersion" (default) and "Generation". (default "ResourceVersion")
>       --dry-run                       Run the command in dry-run mode, without making any server requests.
>       --federation-namespace string   Namespace in the host cluster where the federation system components are installed.  This namespace will also be the target of propagation if the controller manager is configured with --limited-scope and clusters are joined with --limited-scope. (default "federation-system")
>   -f, --filename string               If provided, the command will be configured from the provided yaml file.  Only --output wll be accepted from the command line
>   -h, --help                          help for enable
>       --host-cluster-context string   Host cluster context
>       --kubeconfig string             Path to the kubeconfig file to use for CLI requests.
>   -o, --output string                 If provided, the resources that will be created in the API will be output to stdout in the provided format.  Valid values are ['yaml'].
>       --primitive-group string        The name of the API group to use for generated federation primitives. (default "primitives.federation.k8s.io")
>       --primitive-version string      The API version to use for generated federation primitives. (default "v1alpha1")
>       --registry-namespace string     Namespace in the host cluster where clusters are registered (default "kube-multicluster-public")
>       --version string                Optional, the API version of the target type.
> 
> Global Flags:
>       --alsologtostderr                  log to standard error as well as files
>       --log-backtrace-at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
>       --log-dir string                   If non-empty, write log files in this directory
>       --log-flush-frequency duration     Maximum number of seconds between log flushes (default 5s)
>       --logtostderr                      log to standard error instead of files (default true)
>       --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
>   -v, --v Level                          log level for V logs
>       --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
> 
> unknown flag: --override-paths
> ```

I compile the `kubefed2` by `go build -o bin/kubefed2 cmd/kubefed2/kubefed2.go` with some commit, but I can not tell the commit id now.
$ ./kubefed2 version
kubefed2 version: version.Info{Version:"v0.0.1-alpha.0", GitCommit:"unknown", GitTreeState:"unknown", BuildDate:"unknown", GoVersion:"go1.11", Compiler:"gc", Platform:"linux/amd64"}
The version is not correct. If using `make kubefed2`, the version looks more resonable.

Let me reproduce this issue with the kubernetes.

**Comment by qinpingli** [comment]
Do not reproduce this issue with version:
./kubefed2 version
kubefed2 version: version.Info{Version:"v0.0.4", GitCommit:"2cdf5d37240d9b8b33e2715deb75fbb7f9e003ad", GitTreeState:"clean", BuildDate:"2018-12-11T01:26:09Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

$ kubectl logs -f federation-controller-manager-0 -n federation-system
Federation v2 controller-manager version: version.Info{Version:"v0.0.4", GitCommit:"2cdf5d37240d9b8b33e2715deb75fbb7f9e003ad", GitTreeState:"clean", BuildDate:"2018-12-11T01:26:09Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}

So,  I'll close this issue.
